version : '3.1'

services:
  nginx:
    image: nginx:1.19.0
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./work:/var/www/html
    depends_on:
      - php73
  mysql:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
  php73:
    build: ./php
    image: zhong-php73:0.1
    volumes:
      - ./work:/var/www/html
    ports:
      - 9000:9000
  memcached:
    image: memcached:1.6.6-alpine
    ports:
      - 11211:11211
