version : '3.1'

services:
  nginx:
    image: nginx:1.19.0
    ports:
      - 80:80
    volumes:
      - ../conf/nginx/php-fpm/conf.d:/etc/nginx/conf.d
      - ./work:/var/www/html
    depends_on:
      - php73
  nginx-swoole:
    image: nginx:1.19.0
    ports:
      - 8082:80
    volumes:
      - ../conf/nginx/swoole/conf.d:/etc/nginx/conf.d
      - ./work-2:/var/www/html:delegated
    depends_on:
      - php73-swoole
  mysql:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${HOME}/docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
  php73:
    build:
      context: ../images/php
      dockerfile: php-fpm-alpine
    image: zhong/php:7.3.19-fpm-alpine
    volumes:
      - ./work:/var/www/html:delegated
    ports:
      - 9000:9000
  php73-swoole:
    build:
      context: ../images/php
      dockerfile: php-cli-alpine-swoole
    image: zhong/php:7.3.19-swoole-alpine
    command: ash -c "cd /var/www/html && php artisan swoole:http start"
    volumes:
      - ./work-2:/var/www/html:delegated
  memcached:
    image: memcached:1.6.6-alpine
    ports:
      - 11211:11211
